# Generated by Django 4.0.4 on 2022-04-27 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_photography'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photography',
            name='image',
            field=models.ImageField(upload_to='photography/'),
        ),
    ]
