# Generated by Django 4.0.4 on 2022-04-27 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_photography_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='photography',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
