# Generated by Django 4.0.4 on 2022-04-27 11:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_photography_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='profilepic.jpg'),
        ),
        migrations.AlterField(
            model_name='social',
            name='discord',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='social',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='social',
            name='instagram',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='social',
            name='twitter',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='social',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='social',
            name='youtube',
            field=models.URLField(blank=True),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=255)),
                ('preview', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField()),
                ('cover_pic', models.ImageField(upload_to=home.models.cover_pic_path)),
                ('image_1', models.ImageField(blank=True, upload_to=home.models.posts_pic_path)),
                ('image_2', models.ImageField(blank=True, upload_to=home.models.posts_pic_path)),
                ('image_3', models.ImageField(blank=True, upload_to=home.models.posts_pic_path)),
                ('tags', models.CharField(blank=True, max_length=500)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.about')),
            ],
        ),
    ]
