# Generated by Django 4.0.4 on 2022-04-28 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_post_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='social',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
    ]
